### DISCUSSION TITLE
Using an existing secret to specify the config.json file?

### DISCUSSION THREAD

**Discussion by kastl-ars** [renovatebot/helm-charts#1473] [Q&A] [answered]
Hi all,

sorry if I have missed this, but I found no hint in the chart's values.yaml that I can use an existing secret (created outside of the chart) to specify the `config.json` configuration file?

From looking a the chart (currently on the road, hence no way to test it) it might be possible to use `renovate.existingConfigFile` pointing to a file that was mounted from a secret using `extraVolumes` and `etraVolumeMounts`?

Something like this:

```
renovate:
  existingConfigFile: /some/path/config.json
extraVolumes:
  - name: my-own-config
     secret:
       name: renovate-config-secret
extraVolumeMounts:
  - name: my-own-config
    mountPath: /some/path/config.json
    subPath: config.json
```

Am I on the right track?

Kind Regards
Johannes

**Comment by viceice** [comment, marked as answer]
yes, that should work.

**Reply by kastl-ars** [reply]
Thanks Michael!

**Reply by johanneskastl** [reply]
Small change, it needs to be:

```
extraVolumes:
  - name: my-own-config
     secretName: # <<< this must be secretName, not just secret
       name: renovate-config-secret
```

Should I prepare a small PR to add a commented example to the `values.yaml`?
