### ISSUE TITLE
Add a Redis deployment option

### ISSUE THREAD

**Issue by ArmaanT** [renovatebot/helm-charts#113]
Since Renovate can be configured to use Redis for caching, I think it would be helpful to provide an optional Redis deployment and service that would be able to maintain its cache across different instantiations of the main CronJob.

I think a configuration block similar to this would work

```yaml
redis:
  enabled: false
  annotations: {}
  labels: {}
  image:
    repository: redis
    tag: "6"
    pullPolicy: IfNotPresent
```

I'd be happy to make a PR to implement this.
