### ISSUE TITLE
Add optional persistent volume for cacheDir

### ISSUE THREAD

**Issue by cykl** [renovatebot/helm-charts#163]
My understanding is that renovatebot can leverage some cache to speed up execution and make fewer requests to external service but helm charts has no support for a persistent volume that would allow to persist this cache across execution.

I should be able to create the PV outside of the chart and then using extraVolume(Mount)?s, but this kind of workflow is always clunky. It would be great being able to declare a persistent volume as something like as follow and have it automatically mounted.

```yaml
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: xxGi
    storageClass: "xxx"
```

Perhaps baseDir / cacheDir could be automatically set, but it seems perfectly acceptable having to make such configuration.
