### ISSUE TITLE
Volumes in cronjob don't look for: .Values.renovate.persistence.cache.enabled

### ISSUE THREAD

**Issue by KnechtionsCoding** [renovatebot/helm-charts#287]
If you set: `.Values.renovate.persistence.cache.enabled` but not any of these: https://github.com/renovatebot/helm-charts/blob/main/charts/renovate/templates/cronjob.yaml#L95

You end up with broken YAML because the volumes key isn't created for persistence.

values.yaml to reproduce:

```
renovate:
  persistence:
    cache: 
      enabled: false
      storageSize: 40Gi
```
